# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - appveyor.yml
    - .travis.yml
    - lang/*
    - article/*
    - docs/*

jobs:
    

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  
  steps:


  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '3.1.100'

      


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './src/Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@1
    displayName: build
    inputs:
      command: build
      projects: './src/Natasha/Natasha.csproj'
      arguments: '-c Release'


  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test
      projects: './test/NatashaUT'




- job: macOS
  pool:
    vmImage: 'macOS-latest'


  steps:


  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '3.1.100'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './src/Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@1
    displayName: build
    inputs:
      command: build
      projects: './src/Natasha/Natasha.csproj'
      arguments: '-c Release'


  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test
      projects: './test/NatashaUT'




- job: Windows
  pool:
    vmImage: 'windows-latest'


  steps:


  - task: DotNetCoreInstaller@1
    displayName: install
    inputs:
      version: '3.1.100'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './src/Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@1
    displayName: build
    inputs:
      command: build
      projects: './src/Natasha/Natasha.csproj'
      arguments: '-c Release'


  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test
      projects: './test/NatashaUT'